# Generated by Django 4.2.4 on 2025-09-13 04:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacromoleculeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'macromolecule_types',
            },
        ),
        migrations.CreateModel(
            name='Macromolecule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('rec', models.CharField(max_length=255)),
                ('redocking', models.BooleanField(default=True)),
                ('gridsize', models.CharField(blank=True, max_length=255, null=True)),
                ('gridcenter', models.CharField(blank=True, max_length=255, null=True)),
                ('ligante_original', models.CharField(blank=True, max_length=255, null=True)),
                ('rmsd_redocking', models.CharField(blank=True, max_length=255, null=True)),
                ('energia_original', models.CharField(blank=True, max_length=255, null=True)),
                ('pathFilefld', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macromolecules', to='macromolecules.macromoleculetype')),
            ],
            options={
                'db_table': 'macromolecules',
            },
        ),
    ]
