# Generated by Django 4.2.4 on 2025-09-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macromolecules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macromolecule',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macromolecules', to='macromolecules.macromoleculetype'),
        ),
    ]
