# Generated by Django 4.2.4 on 2025-09-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macromolecules', '0002_alter_macromolecule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macromolecule',
            name='redocking',
        ),
        migrations.AddField(
            model_name='macromoleculetype',
            name='redocking',
            field=models.BooleanField(default=True),
        ),
    ]
