# Generated by Django 4.2.4 on 2025-09-13 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('macromolecules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('redocking', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('EM_FILA', 'EM_FILA'), ('PROCESSANDO', 'PROCESSANDO'), ('CONCLUIDO', 'CONCLUIDO'), ('ERROR', 'ERROR')], default='EM_FILA', max_length=20)),
                ('resultado_final', models.JSONField(blank=True, null=True)),
                ('pathFileSDF', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='macromolecules.macromoleculetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processes',
            },
        ),
    ]
