# Generated by Django 4.2.4 on 2025-09-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='redocking',
        ),
    ]
