# Generated by Django 4.2.4 on 2025-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_remove_process_redocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pathFileZIP',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
